#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

export PYTHONPATH="$REPO_DIR:${PYTHONPATH:-}"
export VLLM_USE_V1="${VLLM_USE_V1:-0}"

export TASK_NAME="${TASK_NAME:-object_counting}"
export TASK_TAG="${TASK_TAG:-object_counting_gfnpo_style}"
export VARIANTS="${VARIANTS:-v1_log_prior}"
export RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"

export TRAIN_STEPS="${TRAIN_STEPS:-200}"
export BATCH_SIZE="${BATCH_SIZE:-4}"
export GRAD_ACC_STEPS="${GRAD_ACC_STEPS:-4}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-150}"
export NUM_EXAMPLE="${NUM_EXAMPLE:-5}"
export FEWSHOT_STRATEGY="${FEWSHOT_STRATEGY:-random}"
export FEWSHOT_RESAMPLE_EACH_STEP="${FEWSHOT_RESAMPLE_EACH_STEP:-1}"
export SEED="${SEED:-2}"

export BBH_TRAIN_SIZE="${BBH_TRAIN_SIZE:-50}"
export BBH_TEST_SIZE="${BBH_TEST_SIZE:-100}"
export BBH_REASONING_MAX_TOKENS="${BBH_REASONING_MAX_TOKENS:-1024}"
export BBH_ANSWER_MAX_TOKENS="${BBH_ANSWER_MAX_TOKENS:-1}"
export TEST_EVAL_PERIOD="${TEST_EVAL_PERIOD:-10}"
export EXPORT_EVERY="${EXPORT_EVERY:-10}"
export LOG_EVERY="${LOG_EVERY:-10}"

export PRIOR_REDUCTION="${PRIOR_REDUCTION:-mean}"
export PRIOR_CHUNK_SIZE="${PRIOR_CHUNK_SIZE:-2}"
export GAMMA="${GAMMA:-1.0}"

export ONLINE_RATIO="${ONLINE_RATIO:-0.5}"
export OFFLINE_START_STEP="${OFFLINE_START_STEP:-100}"
export TRAIN_BUFFER_MAX_SIZE="${TRAIN_BUFFER_MAX_SIZE:-1000}"
export CONDITION_QUEUE_SAMPLES="${CONDITION_QUEUE_SAMPLES:-1}"
export CONDITION_BUFFER_SAMPLES="${CONDITION_BUFFER_SAMPLES:-1}"

export EVAL_GPU_MEMORY_UTILIZATION="${EVAL_GPU_MEMORY_UTILIZATION:-0.9}"
export EVAL_MAX_NUM_SEQS="${EVAL_MAX_NUM_SEQS:-8}"
export EVAL_MAX_SEQ_LEN_TO_CAPTURE="${EVAL_MAX_SEQ_LEN_TO_CAPTURE:-3072}"
export EVAL_CHUNK_SIZE="${EVAL_CHUNK_SIZE:-32}"

echo "Running debug object_counting variants with:"
echo "  VARIANTS=$VARIANTS"
echo "  FEWSHOT_STRATEGY=$FEWSHOT_STRATEGY"
echo "  FEWSHOT_RESAMPLE_EACH_STEP=$FEWSHOT_RESAMPLE_EACH_STEP"
echo "  PRIOR_REDUCTION=$PRIOR_REDUCTION"
echo "  GAMMA=$GAMMA"
echo "  BBH_REASONING_MAX_TOKENS=$BBH_REASONING_MAX_TOKENS"

bash "$SCRIPT_DIR/run_debugging_gflownet_variants_200.sh"
